name: "vis-powerdaemon"
description: "Execute power actions on a Pterodactyl Panel instance or compatible API."
author: "VI Software"

inputs:
    PANEL_URL:
        description: "URL of the Pterodactyl panel"
        required: true

    API_KEY:
        description: "Bearer token for panel authorization"
        required: true

    SERVER_ID:
        description: "ID of the server to perform actions on"
        required: true

    POWER_ACTION:
        description: 'Power action to perform (options: "start", "stop", "restart", "kill")'
        required: false
        default: "restart"

runs:
    using: "node16"
    main: "dist/index.js"

branding:
    icon: "power"
    color: "green"
